version: '3'

services:
  server:
    restart: always
    container_name: cat_facial_detection
    image: cat_facial_detection:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ./static:/app/static
      - ./media:/app/media